#!/usr/bin/env python3
"""
Generate the Level-3 exhaustiveness certifier (05-solver-inputs/certify_exhaustiveness.sing)
mechanically from the certified family list, instead of by hand.

Previously this .sing file had no generator anywhere in the bundle and encoded
the same duplicate-branch problem fixed in generate_and_certify.py (many of its
49 embedded "family ideals" were textually identical copies). This script reads
the deduped certificates in 03-certificates/ and emits one family ideal per
DISTINCT branch, restating the degree<=4 ansatz independently (same convention
as verify_certificates.py: discovery, verification, and this exhaustiveness
input are deliberately separate programs).

Family ideal for a branch is built by clearing denominators in its recorded
'solution' map: var = num/den  ->  generator  den*var - num. Branches whose
solution used a free-parameter denominator (recorded in 'exceptional_factors')
get their family ideal saturated at that factor, since the family is only
valid where the factor is nonzero.
"""
import json
from pathlib import Path
from sympy import symbols, expand, fraction, together, sympify

ROOT = Path(__file__).resolve().parent.parent
CERT_DIR = ROOT / '03-certificates'
SOLVER_DIR = ROOT / '05-solver-inputs'

x, y, z = symbols('x y z')


def monos(weight, maxdeg):
    out = []
    for i in range(maxdeg + 1):
        for j in range(maxdeg + 1):
            for k in range(maxdeg + 1):
                if 0 < i + j + k <= maxdeg and i - j - 2 * k == weight:
                    out.append(x**i * y**j * z**k)
    return out


def build_ideal(D=4):
    from sympy import Matrix, diff, Poly
    m1 = [m for m in monos(-2, D) if m != z]
    m2 = [m for m in monos(-1, D) if m != y]
    m3 = [m for m in monos(1, D) if m != x]
    A = symbols(f'a0:{len(m1)}'); B = symbols(f'b0:{len(m2)}'); C = symbols(f'c0:{len(m3)}')
    F1 = z + sum(a * m for a, m in zip(A, m1))
    F2 = y + sum(b * m for b, m in zip(B, m2))
    F3 = x + sum(c * m for c, m in zip(C, m3))
    unknowns = list(A) + list(B) + list(C)
    J = Matrix([[diff(F, v) for v in (x, y, z)] for F in (F1, F2, F3)])
    det = expand(J.det())
    eqs = [c for m, c in Poly(det, x, y, z).terms() if m != (0, 0, 0)]
    return unknowns, eqs


def family_ideal_generators(unknowns_by_name, solution):
    gens = []
    for var_name, expr_str in solution.items():
        var = unknowns_by_name[var_name]
        num, den = fraction(together(sympify(expr_str)))
        gens.append(expand(den * var - num))
    return gens


def load_branches():
    branches = []
    for fname in ('deg4_main_branches.json', 'deg4_b0_stratum.json'):
        for c in json.load(open(CERT_DIR / fname)):
            branches.append(c)
    return branches


def emit(path):
    unknowns, eqs = build_ideal(4)
    unknowns_by_name = {str(u): u for u in unknowns}
    vars_str = ','.join(str(u) for u in unknowns)
    polys = ',\n  '.join(str(e) for e in eqs)

    branches = load_branches()
    lines = []
    lines.append('// AUTO-GENERATED by 04-scripts/emit_exhaustiveness_check.py -- do not hand-edit.')
    lines.append('// Success criterion printed at end: EXHAUSTIVE iff every minimal prime')
    lines.append('// contains some family ideal (V(P) subset family closure), AND every')
    lines.append('// family ideal lies inside V(I) (soundness, direction A below).')
    # NB: only primdec.lib is loaded -- elim.lib redefines several of its
    # procedures (including 'sat' itself) under the same names, which would
    # silently swap in a different, incompatible implementation.
    lines.append('LIB "primdec.lib";')
    lines.append(f'ring R = 0, ({vars_str}), dp;')
    lines.append(f'ideal I =\n  {polys};')
    lines.append('list L = minAssGTZ(I);')
    lines.append('int nc = size(L); print("minimal primes: " + string(nc));')

    n = len(branches)
    for j, c in enumerate(branches):
        gens = family_ideal_generators(unknowns_by_name, c['solution'])
        gens_str = ','.join(f'({g})' for g in gens)
        lines.append(f'ideal J{j} = {gens_str};')
        for factor in c.get('exceptional_factors', []):
            # NB: must assign sat()'s returned list to a variable before
            # indexing -- chaining sat(...)[1] directly on the call silently
            # returns a wrong/truncated ideal in this Singular version.
            lines.append(f'list J{j}sat = sat(J{j}, ideal({factor}));')
            lines.append(f'J{j} = J{j}sat[1];')

    lines.append(f'int i,j; int allcov = 1;')
    lines.append('for (i=1; i<=nc; i++) {')
    lines.append('  ideal P = std(L[i]); int cov = 0;')
    lines.append(f'  for (j=0; j<{n}; j++) {{')
    lines.append('    ideal Jj;')
    lines.append('    execute("Jj = J" + string(j) + ";");')
    lines.append('    if (size(reduce(Jj, P)) == 0) { cov = 1; print("component " + string(i) + " covered by family " + string(j)); break; }')
    lines.append('  }')
    lines.append('  if (cov == 0) { allcov = 0; print("component " + string(i) + " NOT covered: "); L[i]; }')
    lines.append('}')
    lines.append('// Direction A (soundness): each family lies in V(I)')
    lines.append('int snd = 1;')
    lines.append(f'for (j=0; j<{n}; j++) {{')
    lines.append('  ideal Jj; execute("Jj = J" + string(j) + ";");')
    lines.append('  if (size(reduce(I, std(Jj))) != 0) { snd = 0; print("family " + string(j) + " NOT inside V(I)"); }')
    lines.append('}')
    lines.append('if (allcov && snd) { print("RESULT: EXHAUSTIVE -- classification unconditional"); }')
    lines.append('else { print("RESULT: GAP FOUND -- report components above"); }')
    lines.append('quit;')

    path.write_text('\n'.join(lines) + '\n')
    print(f'wrote {path} with {n} distinct family ideals ({n} branches, 0 duplicates by construction)')


if __name__ == '__main__':
    emit(SOLVER_DIR / 'certify_exhaustiveness.sing')
